openvpn_pkg: openvpn
openvpn_service: openvpn-server@server
openvpn_port: 1194
openvpn_proto: udp
openvpn_dev: tun
openvpn_cipher: "AES-256-GCM"
openvpn_auth: "SHA256"
openvpn_use_tls_crypt: true
openvpn_pki_dir: /etc/openvpn/pki
openvpn_manage_iptables: true
openvpn_enable_ip_forward: true
openvpn_nat_interface: eth0
openvpn_push_routes: []
openvpn_server: "10.8.0.0 255.255.255.0"